/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/app/App.vue')['default']
    DefaultPage: typeof import('./src/pages/DefaultPage.vue')['default']
    LoginPage: typeof import('./src/pages/auth/LoginPage.vue')['default']
    RegisterPage: typeof import('./src/pages/auth/RegisterPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignUpPage: typeof import('./src/pages/auth/SignUpPage.vue')['default']
  }
}
